In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import preprocessing 
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support,classification_report
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [14]:
df = pd.read_csv("Datasets/Bankloan.csv")

In [33]:
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,30,blue-collar,married,basic.9y,no,yes,no,cellular,may,fri,...,2,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1,no
1,39,services,single,high.school,no,no,no,telephone,may,fri,...,4,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
2,25,services,married,high.school,no,yes,no,telephone,jun,wed,...,1,999,0,nonexistent,1.4,94.465,-41.8,4.962,5228.1,no
3,38,services,married,basic.9y,no,unknown,unknown,telephone,jun,fri,...,3,999,0,nonexistent,1.4,94.465,-41.8,4.959,5228.1,no
4,47,admin.,married,university.degree,no,yes,no,cellular,nov,mon,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.191,5195.8,no
5,32,services,single,university.degree,no,no,no,cellular,sep,thu,...,3,999,2,failure,-1.1,94.199,-37.5,0.884,4963.6,no
6,32,admin.,single,university.degree,no,yes,no,cellular,sep,mon,...,4,999,0,nonexistent,-1.1,94.199,-37.5,0.879,4963.6,no
7,41,entrepreneur,married,university.degree,unknown,yes,no,cellular,nov,mon,...,2,999,0,nonexistent,-0.1,93.200,-42.0,4.191,5195.8,no
8,31,services,divorced,professional.course,no,no,no,cellular,nov,tue,...,1,999,1,failure,-0.1,93.200,-42.0,4.153,5195.8,no
9,35,blue-collar,married,basic.9y,unknown,no,no,telephone,may,thu,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
10,25,services,single,basic.6y,unknown,yes,no,cellular,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.958,5228.1,no
11,36,self-employed,single,basic.4y,no,no,no,cellular,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.968,5228.1,no
12,36,admin.,married,high.school,no,no,no,telephone,may,wed,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.859,5191.0,no
13,47,blue-collar,married,basic.4y,no,yes,no,telephone,jun,thu,...,2,999,0,nonexistent,1.4,94.465,-41.8,4.958,5228.1,no
14,29,admin.,single,high.school,no,no,no,cellular,may,fri,...,2,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1,no
15,27,services,single,university.degree,no,no,no,cellular,jul,wed,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,no
16,44,admin.,divorced,university.degree,no,no,no,cellular,jul,wed,...,6,999,0,nonexistent,1.4,93.918,-42.7,4.957,5228.1,no
17,46,admin.,divorced,university.degree,no,yes,no,telephone,jul,mon,...,4,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
18,45,entrepreneur,married,university.degree,unknown,yes,yes,cellular,aug,mon,...,2,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,no
19,50,blue-collar,married,basic.4y,no,no,yes,cellular,jul,tue,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.961,5228.1,yes
20,55,services,married,basic.6y,unknown,yes,no,cellular,jul,tue,...,6,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
21,39,technician,divorced,high.school,no,no,no,cellular,mar,mon,...,1,12,2,success,-1.8,93.369,-34.8,0.639,5008.7,yes
22,29,technician,single,university.degree,no,yes,yes,cellular,aug,wed,...,3,999,0,nonexistent,1.4,93.444,-36.1,4.967,5228.1,no
23,40,management,married,high.school,no,no,yes,cellular,aug,wed,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,no
24,44,technician,married,professional.course,unknown,yes,no,telephone,may,fri,...,7,999,0,nonexistent,1.1,93.994,-36.4,4.864,5191.0,no
25,38,technician,married,professional.course,no,yes,no,cellular,aug,mon,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,yes
26,36,technician,divorced,professional.course,no,no,no,telephone,may,wed,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.856,5191.0,no
27,28,blue-collar,married,basic.6y,unknown,no,no,cellular,may,mon,...,2,999,1,failure,-1.8,92.893,-46.2,1.299,5099.1,no
28,47,admin.,single,unknown,unknown,no,no,telephone,may,thu,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.860,5191.0,no
29,34,admin.,married,university.degree,no,no,no,cellular,aug,tue,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4089,25,admin.,single,university.degree,no,yes,yes,cellular,oct,fri,...,1,999,1,failure,-3.4,92.431,-26.9,0.739,5017.5,yes
4090,43,blue-collar,married,basic.4y,unknown,yes,yes,telephone,may,tue,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4091,38,management,married,high.school,unknown,no,no,telephone,may,thu,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.860,5191.0,no
4092,30,blue-collar,single,high.school,no,no,no,telephone,jul,wed,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.956,5228.1,no
4093,56,retired,married,basic.4y,unknown,no,no,cellular,jul,tue,...,3,999,0,nonexistent,1.4,93.918,-42.7,4.961,5228.1,no
4094,62,blue-collar,married,basic.4y,no,yes,no,cellular,nov,mon,...,1,6,1,success,-3.4,92.649,-30.1,0.719,5017.5,no
4095,36,admin.,single,university.degree,no,no,yes,cellular,aug,fri,...,2,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,no
4096,33,services,married,high.school,no,no,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4097,41,blue-collar,divorced,basic.9y,no,no,no,cellular,aug,tue,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,no
4098,34,housemaid,single,university.degree,no,yes,no,cellular,aug,thu,...,3,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,no
4099,58,admin.,divorced,high.school,no,no,no,cellular,aug,tue,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,no
4100,41,admin.,divorced,high.school,no,no,no,cellular,apr,fri,...,1,999,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,no
4101,35,entrepreneur,single,university.degree,no,yes,no,cellular,jul,mon,...,5,999,0,nonexistent,1.4,93.918,-42.7,4.960,5228.1,no
4102,31,blue-collar,single,basic.9y,unknown,no,yes,telephone,jun,fri,...,2,999,0,nonexistent,1.4,94.465,-41.8,4.959,5228.1,no
4103,43,services,married,high.school,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4104,42,technician,divorced,professional.course,no,yes,no,cellular,aug,mon,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.970,5228.1,no
4105,47,housemaid,married,basic.4y,unknown,yes,no,telephone,jul,tue,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.961,5228.1,no
4106,45,entrepreneur,divorced,basic.9y,no,yes,no,cellular,may,tue,...,3,999,0,nonexistent,-1.8,92.893,-46.2,1.344,5099.1,no
4107,36,admin.,married,university.degree,unknown,yes,no,cellular,aug,wed,...,11,999,0,nonexistent,1.4,93.444,-36.1,4.964,5228.1,no
4108,32,admin.,married,university.degree,no,yes,no,telephone,may,thu,...,5,999,0,nonexistent,-1.8,92.893,-46.2,1.266,5099.1,no
4109,63,retired,married,high.school,no,no,no,cellular,oct,wed,...,1,999,0,nonexistent,-3.4,92.431,-26.9,0.740,5017.5,no
4110,53,housemaid,divorced,basic.6y,unknown,unknown,unknown,telephone,may,fri,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
4111,30,technician,married,university.degree,no,no,yes,cellular,jun,fri,...,1,999,1,failure,-1.7,94.055,-39.8,0.748,4991.6,no
4112,31,technician,single,professional.course,no,yes,no,cellular,nov,thu,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.076,5195.8,no
4113,31,admin.,single,university.degree,no,yes,no,cellular,nov,thu,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.076,5195.8,no
4114,30,admin.,married,basic.6y,no,yes,yes,cellular,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.958,5228.1,no
4115,39,admin.,married,high.school,no,yes,no,telephone,jul,fri,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.959,5228.1,no
4116,27,student,single,high.school,no,no,no,cellular,may,mon,...,2,999,1,failure,-1.8,92.893,-46.2,1.354,5099.1,no
4117,58,admin.,married,high.school,no,no,no,cellular,aug,fri,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.966,5228.1,no
4118,34,management,single,high.school,no,yes,no,cellular,nov,wed,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.120,5195.8,no

In [34]:
df['poutcome'].value_counts()

nonexistent    3523
failure         454
success         142
Name: poutcome, dtype: int64

In [16]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [17]:
le = preprocessing.LabelEncoder()
df2 = df.apply(le.fit_transform)
df2

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,12,1,1,2,0,2,0,0,6,0,...,1,20,0,1,3,8,4,156,6,0
1,21,7,2,3,0,0,0,1,6,0,...,3,20,0,1,8,18,16,207,8,0
2,7,7,1,3,0,2,0,1,4,4,...,0,20,0,1,9,23,8,225,10,0
3,20,7,1,2,0,1,1,1,4,0,...,2,20,0,1,9,23,8,222,10,0
4,29,0,1,6,0,2,0,0,7,1,...,0,20,0,1,7,11,7,201,9,0
5,14,7,2,6,0,0,0,0,9,2,...,2,20,2,0,5,21,15,97,0,0
6,14,0,2,6,0,2,0,0,9,1,...,3,20,0,1,5,21,15,93,0,0
7,23,2,1,6,1,2,0,0,7,1,...,1,20,0,1,7,11,7,201,9,0
8,13,7,0,5,0,0,0,0,7,3,...,0,20,1,0,7,11,7,200,9,0
9,17,1,1,2,1,0,0,1,6,2,...,0,20,0,1,8,18,16,207,8,0
10,7,7,2,1,1,2,0,0,3,2,...,0,20,0,1,9,17,6,221,10,0
11,18,6,2,0,0,0,0,0,3,2,...,0,20,0,1,9,17,6,231,10,0
12,18,0,1,3,0,0,0,1,6,4,...,1,20,0,1,8,18,16,211,8,0
13,29,1,1,0,0,2,0,1,4,2,...,1,20,0,1,9,23,8,221,10,0
14,11,0,2,3,0,0,0,0,6,0,...,1,20,0,1,3,8,4,156,6,0
15,9,7,2,6,0,0,0,0,3,4,...,1,20,0,1,9,17,6,226,10,0
16,26,0,0,6,0,0,0,0,3,4,...,5,20,0,1,9,17,6,220,10,0
17,28,0,0,6,0,2,0,1,3,1,...,3,20,0,1,9,17,6,225,10,0
18,27,2,1,6,1,2,2,0,1,1,...,1,20,0,1,9,13,17,228,10,0
19,32,1,1,0,0,0,2,0,3,3,...,0,20,0,1,9,17,6,224,10,1
20,37,7,1,1,1,2,0,0,3,3,...,5,20,0,1,9,17,6,225,10,0
21,21,9,0,3,0,0,0,0,5,1,...,0,11,2,2,3,12,18,3,2,1
22,11,9,2,6,0,2,2,0,1,4,...,2,20,0,1,9,13,17,230,10,0
23,22,4,1,3,0,0,2,0,1,4,...,0,20,0,1,9,13,17,228,10,0
24,26,9,1,5,1,2,0,1,6,0,...,6,20,0,1,8,18,16,213,8,0
25,20,9,1,5,0,2,0,0,1,1,...,0,20,0,1,9,13,17,228,10,1
26,18,9,0,5,0,0,0,1,6,4,...,0,20,0,1,8,18,16,208,8,0
27,10,1,1,1,1,0,0,0,6,1,...,1,20,1,0,3,8,4,155,6,0
28,29,0,2,7,1,0,0,1,6,2,...,0,20,0,1,8,18,16,212,8,0
29,16,0,1,6,0,0,0,0,1,3,...,0,20,0,1,9,13,17,226,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4089,7,0,2,6,0,2,2,0,8,0,...,0,20,1,0,0,2,25,49,3,1
4090,25,1,1,0,1,2,2,1,6,3,...,1,20,0,1,8,18,16,209,8,0
4091,20,4,1,3,1,0,0,1,6,2,...,1,20,0,1,8,18,16,212,8,0
4092,12,1,2,3,0,0,0,1,3,4,...,0,20,0,1,9,17,6,219,10,0
4093,38,5,1,0,1,0,0,0,3,3,...,2,20,0,1,9,17,6,224,10,0
4094,44,1,1,0,0,2,0,0,7,1,...,0,6,1,2,0,4,23,37,3,0
4095,18,0,2,6,0,0,2,0,1,0,...,1,20,0,1,9,13,17,226,10,0
4096,15,7,1,3,0,0,0,1,6,1,...,1,20,0,1,8,18,16,209,8,0
4097,23,1,0,2,0,0,0,0,1,3,...,0,20,0,1,9,13,17,226,10,0
4098,16,3,2,6,0,2,0,0,1,2,...,2,20,0,1,9,13,17,226,10,0
4099,40,0,0,3,0,0,0,0,1,3,...,0,20,0,1,9,13,17,226,10,0
4100,23,0,0,3,0,0,0,0,0,0,...,0,20,0,1,3,10,3,166,6,0
4101,17,2,2,6,0,2,0,0,3,1,...,4,20,0,1,9,17,6,223,10,0
4102,13,1,2,2,1,0,2,1,4,0,...,1,20,0,1,9,23,8,222,10,0
4103,25,7,1,3,0,0,0,1,6,1,...,0,20,0,1,8,18,16,209,8,0
4104,24,9,0,5,0,2,0,0,1,1,...,0,20,0,1,9,13,17,232,10,0
4105,29,3,1,0,1,2,0,1,3,3,...,1,20,0,1,9,17,6,224,10,0
4106,27,2,0,2,0,2,0,0,6,3,...,2,20,0,1,3,8,4,159,6,0
4107,18,0,1,6,1,2,0,0,1,4,...,10,20,0,1,9,13,17,227,10,0
4108,14,0,1,6,0,2,0,1,6,2,...,4,20,0,1,3,8,4,150,6,0
4109,45,5,1,3,0,0,0,0,8,4,...,0,20,0,1,0,2,25,50,3,0
4110,35,3,0,1,1,1,1,1,6,0,...,1,20,0,1,8,18,16,207,8,0
4111,12,9,1,6,0,0,2,0,4,0,...,0,20,1,0,4,20,13,53,1,0
4112,13,9,2,5,0,2,0,0,7,2,...,0,20,0,1,7,11,7,198,9,0
4113,13,0,2,6,0,2,0,0,7,2,...,0,20,0,1,7,11,7,198,9,0
4114,12,0,1,1,0,2,2,0,3,2,...,0,20,0,1,9,17,6,221,10,0
4115,21,0,1,3,0,2,0,1,3,0,...,0,20,0,1,9,17,6,222,10,0
4116,9,8,2,3,0,0,0,0,6,1,...,1,20,1,0,3,8,4,160,6,0
4117,40,0,1,3,0,0,0,0,1,0,...,0,20,0,1,9,13,17,229,10,0
4118,16,4,2,3,0,2,0,0,7,4,...,0,20,0,1,7,11,7,199,9,0

In [25]:
X = df2.drop('y', axis=1)
Y = df2['y']
xtrain, xtest, ytrain, ytest = train_test_split(X,Y,test_size = 0.25, random_state=0)
print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)
print(ytest.shape)

(3089, 20)
(3089,)
(1030, 20)
(1030,)

In [26]:
df2.dtypes

age               int64
job               int64
marital           int64
education         int64
default           int64
housing           int64
loan              int64
contact           int64
month             int64
day_of_week       int64
duration          int64
campaign          int64
pdays             int64
previous          int64
poutcome          int64
emp.var.rate      int64
cons.price.idx    int64
cons.conf.idx     int64
euribor3m         int64
nr.employed       int64
y                 int64
dtype: object

In [27]:
# Feature extraction
model = LogisticRegression()
#rfe = RFE(model, 3)
rfe = RFE(model)
fit = rfe.fit(xtrain,ytrain)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

Num Features: 10
Selected Features: [False False False False  True False False  True  True False False  True
  True  True  True  True  True  True False False]
Feature Ranking: [ 9 10  6  4  1  2 11  1  1  3  8  1  1  1  1  1  1  1  7  5]

/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [30]:
ypred=rfe.predict(xtest)
print("Accuracy:",accuracy_score(ytest, ypred))
print("Error Rate:",1-accuracy_score(ytest, ypred))

Accuracy: 0.9
Error Rate: 0.1

In [31]:
confusion_matrix(ytest,ypred)

array([[913,  16],
       [ 87,  14]])

In [32]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.91      0.98      0.95       929
           1       0.47      0.14      0.21       101

   micro avg       0.90      0.90      0.90      1030
   macro avg       0.69      0.56      0.58      1030
weighted avg       0.87      0.90      0.87      1030